if(NOT DEFINED TEST_EXECUTABLE)
    message(FATAL_ERROR "TEST_EXECUTABLE is required")
endif()
foreach(budget RANGE 0 127)
    execute_process(COMMAND "${TEST_EXECUTABLE}" --prepare-fault-std "${budget}"
        RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE ERROR TIMEOUT 15)
    if(NOT RESULT STREQUAL "0")
        message(FATAL_ERROR "real Worker preparation budget=${budget} failed: result=${RESULT} output=${OUTPUT} error=${ERROR}")
    endif()
    if(ERROR MATCHES "udp-listener-prepare-sweep complete allocations=${budget} budget=${budget}")
        message(STATUS "real Worker preparation sweep passed: ${budget} actual allocation failures preserve old listener; next budget serves replacement")
        return()
    endif()
    if(NOT ERROR MATCHES "udp-listener-fault consumed=std-new hook=${budget} budget=${budget}")
        message(FATAL_ERROR "preparation budget=${budget} did not hit the real allocation hook: ${ERROR}")
    endif()
endforeach()
message(FATAL_ERROR "preparation allocation sweep did not finish within 128 budgets")
